### Get all cats
GET http://127.0.0.1:3000/api/v1/cats


### Get one cat
GET http://127.0.0.1:3000/api/v1/cats/501


### Upload cat with image
POST http://127.0.0.1:3000/api/v1/cats
Content-Type: multipart/form-data; boundary=CatBoundary

--CatBoundary
Content-Disposition: form-data; name="cat_name"

Misu
--CatBoundary
Content-Disposition: form-data; name="weight"

6
--CatBoundary
Content-Disposition: form-data; name="owner"

1001
--CatBoundary
Content-Disposition: form-data; name="birthdate"

2023-10-08
--CatBoundary
Content-Disposition: form-data; name="cat"; filename="cat.jpg"
Content-Type: image/jpeg

< ./public/cat.jpg
--CatBoundary--


### Update cat
PUT http://127.0.0.1:3000/api/v1/cats/501
Content-Type: application/json

{
  "cat_name": "Milo Updated"
}


### Delete cat
DELETE http://127.0.0.1:3000/api/v1/cats/501


### Get all users
GET http://127.0.0.1:3000/api/v1/users


### Get one user
GET http://127.0.0.1:3000/api/v1/users/1001


### Add user
POST http://127.0.0.1:3000/api/v1/users
Content-Type: application/json

{
  "name": "Ayan Ahmed",
  "username": "ayan",
  "email": "ayan@example.com",
  "password": "hello123"
}


### Update user
PUT http://127.0.0.1:3000/api/v1/users/1001
Content-Type: application/json

{
  "name": "Ayan Updated"
}


### Delete user
DELETE http://127.0.0.1:3000/api/v1/users/1001
